
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: test-laravel
      POSTGRES_PASSWORD: testlaravel123
      POSTGRES_DB: tienda
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tienda.com
      PGADMIN_DEFAULT_PASSWORD: testlaravel123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: